#!/usr/bin/env node
/**
 * dsh-dsov-plugin — 构建脚本（零依赖，纯 Node）。
 *
 * 输出到 lib/：
 *   - lib/index.js    Host 端：src/index.js 原样拷贝（ESM，导出 { inject, apply }）。
 *   - lib/client.js   Client 端：把 src/client.js 包装为 web GUI 的 module-loader 包
 *                     （window.__ModuleLoader__.load）。包装的模块 id 取自 package.json 的
 *                     `name`（与 client-modules 的图节点一致），`React` 以 require("react")
 *                     注入（react 是 shell 的 seed 模块）。
 *
 * 使用：npm run build   或   node scripts/build.mjs
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))
const loaderId = pkg.name

mkdirSync(join(root, 'lib'), { recursive: true })

// ── Host 端 ──
const host = readFileSync(join(root, 'src/index.js'), 'utf8')
writeFileSync(
  join(root, 'lib/index.js'),
  `/* generated by scripts/build.mjs — do not edit */\n${host}`,
)

// ── Client 端 ──
const clientBody = readFileSync(join(root, 'src/client.js'), 'utf8')
const client = `/* generated by scripts/build.mjs — do not edit */\n` +
`window.__ModuleLoader__.load({\n` +
`\tid: ${JSON.stringify(loaderId)},\n` +
`\tfactory: (require) => {\n` +
`\t\tvar module = { exports: {} };\n` +
`\t\tvar exports = module.exports;\n` +
`\t\tObject.defineProperty(exports, Symbol.toStringTag, { value: "Module" });\n` +
`\t\tvar React = require("react");\n` +
`${clientBody}\n` +
`\t\texports.inject = inject;\n` +
`\t\texports.apply = apply;\n` +
`\t\treturn module.exports;\n` +
`\t}\n` +
`});\n`
writeFileSync(join(root, 'lib/client.js'), client)

console.log(`[build] lib/index.js  <- src/index.js   (host entry, exports { inject, apply })`)
console.log(`[build] lib/client.js <- src/client.js   (module-loader id = "${loaderId}")`)
console.log('[build] done')
